[mypy]
python_version = 3.10

[mypy-fire.*]
ignore_missing_imports = True

[mypy-hello.*]
ignore_missing_imports = True

[mypy-hello_env.*]
ignore_missing_imports = True

[mypy-calculator_instance_method.*]
ignore_missing_imports = True

[mypy-calculator_class_method.*]
ignore_missing_imports = True
